namespace: service-discovery-dev
nameSuffix: -dev
bases:
- ../base
images:
- name: service_discovery
  newTag: latest
resources:
- flyway-deployment.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- pgdata-persistentvolumeclaim.yaml
vars:
- name: POSTGRES_SERVICE
  objref:
    kind: Service
    name: postgres
    apiVersion: v1
