apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres
  name: postgres
spec:
  ClusterIP: None
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    service: postgres
