steps:
# - name: 'docker/compose:1.24.0'
#   args: ['-f', 'docker-compose.yml', 'up', '-d']

# - name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --target=releaser
#   - --dockerfile=./Dockerfile.cb
#   - --build-arg=BASE_IMAGE=$_BASE_IMAGE
#   - --build-arg=RUNNER_IMAGE=$_RUNNER_IMAGE
#   - --destination=gcr.io/$PROJECT_ID/service_discovery:tester-$BUILD_ID
#   - --cache=true
#   - --cache-ttl=48h

# - name: 'docker:19.03.1'
#   args: ['run', '--network', 'workspace_sd_net', '-e', 'BUILD_ID=$BUILD_ID', '--entrypoint', 'rebar3', 'gcr.io/$PROJECT_ID/service_discovery:tester-$BUILD_ID', 'ct']

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --target=runner
  - --dockerfile=./Dockerfile.cb
  - --build-arg=BASE_IMAGE=$_BASE_IMAGE
  - --build-arg=RUNNER_IMAGE=$_RUNNER_IMAGE
  - --destination=gcr.io/$PROJECT_ID/service_discovery:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=48h

substitutions:
  _BASE_IMAGE: erlang:22.0.2-alpine
  _RUNNER_IMAGE: alpine:3.9
