version: '3'
services:
  postgres:
    image: circleci/postgres:11-alpine-ram
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: discovery
      POSTGRES_USER: discovery
      POSTGRES_PASSWORD: password
    volumes:
    - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:6-alpine
    command:
    - -url=jdbc:postgresql://postgres:5432/discovery
    - -user=discovery
    - -password=password
    - -connectRetries=60
    - migrate
    volumes:
    - ./apps/service_discovery_postgres/priv/migrations:/flyway/sql
    depends_on:
    - postgres

volumes:
  pgdata:
