version: '3'
services:
  postgres:
    image: circleci/postgres:11-alpine-ram
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: discovery
      POSTGRES_USER: discovery
      POSTGRES_PASSWORD: password
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
      - sd_net

  flyway:
    image: boxfuse/flyway:5.2.4
    command:
    - -url=jdbc:postgresql://postgres:5432/discovery
    - -user=discovery
    - -password=password
    - -connectRetries=60
    - migrate
    volumes:
    - ./sql:/flyway/sql
    depends_on:
    - postgres
    networks:
      - sd_net

networks:
  sd_net:
    driver: bridge

volumes:
  pgdata:
