apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-discovery-stage
nameSuffix: -stage
commonLabels:
  overlay: stage
bases:
- ../../base
images:
- name: flyway/flyway
  newName: gcr.io/adoptingerlang/flyway
  newTag: 6-alpine
- name: postgres
  newName: gcr.io/adoptingerlang/postgres
  newTag: 11-alpine
- name: service_discovery
  newName: service_discovery
  newTag: c037c05256a0f6ef82fcff8f83ff982b4ee07079
configMapGenerator:
- env: stage.env
  name: configmap
