version: 2.1
orbs:
  rebar3: tsloughter/rebar3@0.6.4

workflows:
  build-test:
    jobs:
      - rebar3/compile
      - rebar3/xref:
          requires:
            - rebar3/compile
      - rebar3/dialyzer:
          requires:
            - rebar3/compile
      - rebar3/ct:
          pre-steps:
            - setup_remote_docker
            - run:
                command: |
                  set -x
                  docker-compose up -d
          requires:
            - rebar3/compile
      - rebar3/cover:
          requires:
            - rebar3/ct
