version: 2.1

orbs:
  rebar3: tsloughter/rebar3@0.7.0

executors:
  erlang_postgres:
    docker:
      - image: circleci/erlang:22
        entrypoint: ["/bin/sh"]
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: discovery
          POSTGRES_PASSWORD: password
          POSTGRES_DB: discovery

workflows:
  build-test:
    jobs:
      - rebar3/compile
      - rebar3/xref:
          requires:
            - rebar3/compile
      - rebar3/dialyzer:
          requires:
            - rebar3/compile
      - rebar3/ct:
          executor: erlang_postgres
          pre-steps:
            - checkout
            - run:
                command: |
                  wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-linux-x64.tar.gz | tar xvz
                  ./flyway-5.2.4/flyway -url=jdbc:postgresql://localhost:5432/discovery -user=discovery -password=password -connectRetries=60 -locations=filesystem:sql migrate

          requires:
            - rebar3/compile
      - rebar3/cover:
          requires:
            - rebar3/ct
