apiVersion: batch/v1
kind: Job
metadata:
  labels:
    service: flyway
  name: flyway
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        service: flyway
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: migrations
        emptyDir: {}
      containers:
      - args:
        - "-url=jdbc:postgresql://$(POSTGRES_SERVICE):5432/discovery"
        - -user=discovery
        - -password=password
        - -connectRetries=60
        - migrate
        image: boxfuse/flyway:5.2.4
        name: flyway
        volumeMounts:
        - name: migrations
          mountPath: /flyway/sql

      - name: service-discovery
        image: service_discovery-sql
        volumeMounts:
          - name: migrations
            mountPath: /flyway/sql
        command: ["/bin/sh"]
        args: ["-c", "cp /opt/service_discovery/sql/* /flyway/sql"]
