apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-discovery-dev
nameSuffix: -dev
commonLabels:
  overlay: dev
bases:
- ../../base
images:
- name: service_discovery
  newTag: latest
patchesStrategicMerge:
- flyway_job_patch.yaml
configMapGenerator:
- name: configmap
  env: dev.env
