apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-discovery-dev
nameSuffix: -dev
commonLabels:
  overlay: dev
bases:
- ../../base
images:
- name: service_discovery
  newTag: latest
resources:
- postgres-deployment.yaml
- postgres-service.yaml
- pgdata-persistentvolumeclaim.yaml
patchesStrategicMerge:
- flyway_job_patch.yaml
vars:
- fieldref: {}
  name: POSTGRES_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: postgres
configMapGenerator:
- name: configmap
  env: dev.env
