apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-discovery-dev
nameSuffix: -dev
commonLabels:
  overlay: dev
bases:
- ../../base
- ../../postgres
images:
- name: service_discovery
  newName: service_discovery
  newTag: master
patchesStrategicMerge:
- flyway_job_patch.yaml
configMapGenerator:
- env: dev.env
  name: configmap
