apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: migrations
        emptyDir: {}
      initContainers:
      - args:
        - "-url=jdbc:postgresql://$(POSTGRES_SERVICE):5432/discovery"
        - -user=discovery
        - -password=password
        - -connectRetries=60
        - validate
        image: boxfuse/flyway:5.2.4
        name: flyway-validate
        volumeMounts:
        - name: migrations
          mountPath: /flyway/sql

      - name: service-discovery-sql
        image: service_discovery-sql
        volumeMounts:
          - name: migrations
            mountPath: /flyway/sql
        command: ["/bin/sh"]
        args: ["-c", "cp /opt/service_discovery/sql/* /flyway/sql"]
