apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-discovery
commonLabels:
  app: postgres
resources:
- flyway-job.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- pgdata-persistentvolumeclaim.yaml
vars:
- fieldref: {}
  name: POSTGRES_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: postgres
