apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: migrations
        emptyDir:
          medium: Memory
      initContainers:
      - args:
        - "-url=jdbc:postgresql://$(POSTGRES_SERVICE):5432/discovery"
        - -user=discovery
        - -password=password
        - -connectRetries=60
        - validate
        image: boxfuse/flyway:5.2.4
        name: flyway-validate
        volumeMounts:
        - name: migrations
          mountPath: /flyway/sql

      - name: service-discovery-sql
        image: service_discovery_sql
        volumeMounts:
          - name: migrations
            mountPath: /flyway/sql
        command: ["/bin/sh"]
        args: ["-c", "cp /app/sql/* /flyway/sql"]

      containers:
      - name: service-discovery
        image: service_discovery
        ports:
        - containerPort: 8053
          protocol: UDP
          name: dns
        - containerPort: 3000
          protocol: TCP
          name: http
        - containerPort: 8081
          protocol: TCP
          name: grpc
        env:
        - name: DB_HOST
          value: $(POSTGRES_SERVICE)
        - name: SCHEDULERS
          valueFrom:
            resourceFieldRef:
              containerName: service-discovery
              resource: limits.cpu
              divisor: 1
        envFrom:
        - configMapRef:
            name: configmap

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
      
