apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: service-discovery
        image: tsloughter/service_discovery:06f522015c0d4c9ddcba73fdd632cf667cdb482c
        ports:
        - containerPort: 8053
          protocol: UDP
