apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: service-discovery
        image: service_discovery
        ports:
        - containerPort: 8053
          protocol: UDP
