apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  template:
    spec:
      shareProcessNamespace: true
      containers:
      - name: service-discovery
        image: service_discovery
        ports:
        - containerPort: 8053
          protocol: UDP
          name: dns
        - containerPort: 3000
          protocol: TCP
          name: http
        - containerPort: 8081
          protocol: TCP
          name: grpc
        env:
        - name: DB_HOST
          value: $(POSTGRES_SERVICE)
        - name: SCHEDULERS
          valueFrom:
            resourceFieldRef:
              containerName: service-discovery
              resource: limits.cpu
              divisor: 1
        envFrom:
        - configMapRef:
            name: configmap

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
      
