namespace: service-discovery
commonLabels:
  app: service-discovery
commonAnnotations:
  oncallPager: 800-555-1212
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
configMapGenerator:
- name: configmap
  env: default.env
  # envs:
  # - default_env
