namespace: service-discovery
commonLabels:
  app: service-discovery
commonAnnotations:
  oncallPager: 800-555-1212
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
configMapGenerator:
- name: configmap
  # files:
  # - application.properties
  literals:
  - FOO2=Bar2
